# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Hunger Meals' do

pod 'SWRevealViewController', '~> 2.3.0'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit' 
pod 'FBSDKLoginKit'
pod 'Google/SignIn'

pod 'GoogleAuthUtilities'

pod 'MBProgressHUD', '~> 1.0.0'

pod 'JSONModel', '~> 1.2'

pod 'SDWebImage', '~> 3.7'

pod 'IQKeyboardManager', '~> 4.0'

pod 'TwilioSDK', '~>1.2'

pod 'JTCalendar', '~> 2.0'

pod 'GoogleUtilities'

pod 'GoogleNetworkingUtilities'



end

target 'Hunger MealsTests' do

end

target 'Hunger MealsUITests' do

end

