# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Hunger Meals' do

pod 'ECSlidingViewController', '~> 2.0.3'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit' 
pod 'FBSDKLoginKit'
pod 'Google/SignIn'

pod 'JSONModel', '~> 1.2'

pod 'SDWebImage', '~> 3.7'

pod 'Reachability', '~> 3.2'

pod 'IQKeyboardManager', '~> 4.0'

pod 'TwilioSDK', '~>1.2'

end

target 'Hunger MealsTests' do

end

target 'Hunger MealsUITests' do

end

